"""
21_Allocation_Optimization.py

FACTORY ALLOCATION OPTIMIZATION
--------------------------------

Purpose
-------
Takes the allocation candidates generated by Step 20 and determines
the best candidate location for each product.

The optimization considers:

1. Lead-time improvement
2. Lead-time improvement percentage
3. Historical reliability
4. Existing decision score
5. Historical records

Input
-----
Step 20:
    allocation_impact_analysis.csv

Outputs
-------
allocation_optimization.csv
final_allocation_recommendations.csv
optimization_product_summary.csv
optimization_location_summary.csv
"""


from pathlib import Path
import sys
import pandas as pd
import numpy as np


# ======================================================================
# PROJECT PATHS
# ======================================================================

SCRIPT_DIR = Path(__file__).resolve().parent

PROJECT_ROOT = SCRIPT_DIR.parent

DATA_DIR = PROJECT_ROOT / "data"

PROCESSED_DIR = DATA_DIR / "processed"

OUTPUT_DIR = (
    PROCESSED_DIR
    / "factory_allocation"
    / "allocation_optimization"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ======================================================================
# DISPLAY HELPERS
# ======================================================================

def print_header(title):

    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)


def print_section(title):

    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)


# ======================================================================
# FILE DISCOVERY
# ======================================================================

def find_file(filename):
    """
    Recursively search data/processed for a required file.

    This prevents problems caused by slightly different folder
    structures between previous pipeline steps.
    """

    matches = list(
        PROCESSED_DIR.rglob(filename)
    )

    if not matches:
        return None

    # Prefer files inside factory allocation folders
    preferred = [
        path
        for path in matches
        if "factory_allocation" in str(path).lower()
    ]

    if preferred:
        return preferred[0]

    return matches[0]


# ======================================================================
# LOAD STEP 20 DATA
# ======================================================================

def load_impact_data():

    print_section(
        "LOADING STEP 20 ALLOCATION IMPACT DATA"
    )

    filename = "allocation_impact_analysis.csv"

    impact_path = find_file(filename)

    if impact_path is None:

        print(
            "\nERROR: Allocation impact dataset not found."
        )

        print(
            "\nSearched under:"
        )

        print(PROCESSED_DIR)

        print(
            "\nCSV files currently available:"
        )

        csv_files = list(
            PROCESSED_DIR.rglob("*.csv")
        )

        if csv_files:

            for file in csv_files:
                print(f"  {file}")

        else:

            print(
                "  No CSV files found."
            )

        print(
            "\nRun Step 20 first:"
        )

        print(
            "python notebooks/20_Allocation_Impact_Analysis.py"
        )

        sys.exit(1)

    print(
        "\nAllocation impact dataset:"
    )

    print(impact_path)

    df = pd.read_csv(
        impact_path
    )

    print(
        f"\nDataset shape: {df.shape}"
    )

    return df


# ======================================================================
# NORMALIZE COLUMN NAMES
# ======================================================================

def normalize_columns(df):

    df = df.copy()

    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace(
            " ",
            "_",
            regex=False
        )
        .str.replace(
            "-",
            "_",
            regex=False
        )
    )

    return df


# ======================================================================
# FIND COLUMN
# ======================================================================

def find_column(
    df,
    possible_names,
    required=True
):

    for name in possible_names:

        name = name.lower()

        if name in df.columns:

            return name

    if required:

        raise KeyError(
            "\nRequired column not found.\n"
            f"Expected one of: {possible_names}\n\n"
            f"Available columns:\n{list(df.columns)}"
        )

    return None


# ======================================================================
# VALIDATE DATA
# ======================================================================

def validate_data(df):

    print_section(
        "DATA VALIDATION"
    )

    print(
        f"Rows    : {len(df):,}"
    )

    print(
        f"Columns : {len(df.columns)}"
    )

    # --------------------------------------------------------------
    # Product
    # --------------------------------------------------------------

    product_col = find_column(
        df,
        [
            "product_id",
            "product"
        ]
    )

    # --------------------------------------------------------------
    # Location
    # --------------------------------------------------------------

    location_col = find_column(
        df,
        [
            "candidate_location",
            "location",
            "location_key"
        ]
    )

    # --------------------------------------------------------------
    # Current lead time
    # --------------------------------------------------------------

    current_lt_col = find_column(
        df,
        [
            "current_avg_lead_time",
            "current_lead_time"
        ]
    )

    # --------------------------------------------------------------
    # Candidate lead time
    # --------------------------------------------------------------

    candidate_lt_col = find_column(
        df,
        [
            "candidate_avg_lead_time",
            "candidate_lead_time"
        ]
    )

    # --------------------------------------------------------------
    # Improvement days
    # --------------------------------------------------------------

    improvement_col = find_column(
        df,
        [
            "lead_time_improvement_days",
            "improvement_days"
        ]
    )

    # --------------------------------------------------------------
    # Improvement percentage
    # --------------------------------------------------------------

    improvement_pct_col = find_column(
        df,
        [
            "lead_time_improvement_pct",
            "improvement_pct"
        ]
    )

    # --------------------------------------------------------------
    # Historical records
    # --------------------------------------------------------------

    records_col = find_column(
        df,
        [
            "candidate_records",
            "records"
        ]
    )

    # --------------------------------------------------------------
    # Decision score
    # --------------------------------------------------------------

    score_col = find_column(
        df,
        [
            "decision_score",
            "candidate_score"
        ],
        required=False
    )

    print(
        f"\nProduct column      : {product_col}"
    )

    print(
        f"Location column     : {location_col}"
    )

    print(
        f"Current lead time   : {current_lt_col}"
    )

    print(
        f"Candidate lead time : {candidate_lt_col}"
    )

    print(
        f"Improvement days    : {improvement_col}"
    )

    print(
        f"Improvement %       : {improvement_pct_col}"
    )

    print(
        f"Candidate records   : {records_col}"
    )

    print(
        f"Decision score      : {score_col}"
    )

    return {

        "product": product_col,

        "location": location_col,

        "current_lt": current_lt_col,

        "candidate_lt": candidate_lt_col,

        "improvement": improvement_col,

        "improvement_pct": improvement_pct_col,

        "records": records_col,

        "score": score_col
    }


# ======================================================================
# CLEAN NUMERIC DATA
# ======================================================================

def clean_numeric_columns(
    df,
    columns
):

    df = df.copy()

    for col in columns:

        if col is None:
            continue

        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        )

    return df


# ======================================================================
# FILTER CANDIDATES
# ======================================================================

def filter_candidates(
    df,
    cols
):

    print_section(
        "FILTERING ALLOCATION CANDIDATES"
    )

    df = df.copy()

    numeric_cols = [

        cols["current_lt"],

        cols["candidate_lt"],

        cols["improvement"],

        cols["improvement_pct"],

        cols["records"],

        cols["score"]
    ]

    df = clean_numeric_columns(
        df,
        numeric_cols
    )

    initial_count = len(df)

    # --------------------------------------------------------------
    # Valid product and location
    # --------------------------------------------------------------

    df = df[
        df[cols["product"]].notna()
        &
        df[cols["location"]].notna()
    ]

    # --------------------------------------------------------------
    # Positive improvement
    # --------------------------------------------------------------

    df = df[
        df[cols["improvement"]] > 0
    ]

    # --------------------------------------------------------------
    # Candidate must actually be faster
    # --------------------------------------------------------------

    df = df[
        df[cols["candidate_lt"]]
        <
        df[cols["current_lt"]]
    ]

    # --------------------------------------------------------------
    # Minimum historical evidence
    # --------------------------------------------------------------

    df = df[
        df[cols["records"]] >= 20
    ]

    # --------------------------------------------------------------
    # Decision score
    #
    # IMPORTANT:
    # This is the corrected expression.
    # --------------------------------------------------------------

    if cols["score"] is not None:

        df = df[
            df[cols["score"]] > 0
        ]

    df = df.reset_index(
        drop=True
    )

    print(
        f"Initial candidates : {initial_count}"
    )

    print(
        f"Qualifying         : {len(df)}"
    )

    if len(df) == 0:

        raise ValueError(
            "\nNo qualifying allocation candidates "
            "remain after filtering."
        )

    return df


# ======================================================================
# CALCULATE OPTIMIZATION SCORE
# ======================================================================

def calculate_optimization_score(
    df,
    cols
):

    print_section(
        "CALCULATING OPTIMIZATION SCORE"
    )

    df = df.copy()

    # --------------------------------------------------------------
    # Lead-time improvement score
    # Weight = 40%
    # --------------------------------------------------------------

    max_improvement = df[
        cols["improvement"]
    ].max()

    if (
        pd.notna(max_improvement)
        and max_improvement > 0
    ):

        df["lead_time_score"] = (

            df[cols["improvement"]]
            /
            max_improvement
        ) * 100

    else:

        df["lead_time_score"] = 0.0

    # --------------------------------------------------------------
    # Improvement percentage score
    # Weight = 25%
    # --------------------------------------------------------------

    max_pct = df[
        cols["improvement_pct"]
    ].max()

    if (
        pd.notna(max_pct)
        and max_pct > 0
    ):

        df["improvement_pct_score"] = (

            df[cols["improvement_pct"]]
            /
            max_pct
        ) * 100

    else:

        df["improvement_pct_score"] = 0.0

    # --------------------------------------------------------------
    # Historical reliability
    # Weight = 20%
    # --------------------------------------------------------------

    max_records = df[
        cols["records"]
    ].max()

    if (
        pd.notna(max_records)
        and max_records > 0
    ):

        df["reliability_score"] = (

            df[cols["records"]]
            /
            max_records
        ) * 100

    else:

        df["reliability_score"] = 0.0

    # --------------------------------------------------------------
    # Existing decision score
    # Weight = 15%
    # --------------------------------------------------------------

    if cols["score"] is not None:

        max_decision = df[
            cols["score"]
        ].max()

        if (
            pd.notna(max_decision)
            and max_decision > 0
        ):

            df["historical_decision_score"] = (

                df[cols["score"]]
                /
                max_decision
            ) * 100

        else:

            df["historical_decision_score"] = 0.0

    else:

        df["historical_decision_score"] = 0.0

    # --------------------------------------------------------------
    # Final optimization score
    #
    # 40% Lead-time improvement
    # 25% Improvement percentage
    # 20% Reliability
    # 15% Existing decision score
    # --------------------------------------------------------------

    df["optimization_score"] = (

        0.40
        *
        df["lead_time_score"]

        +

        0.25
        *
        df["improvement_pct_score"]

        +

        0.20
        *
        df["reliability_score"]

        +

        0.15
        *
        df["historical_decision_score"]
    )

    df["optimization_score"] = (

        df["optimization_score"]
        .clip(
            lower=0,
            upper=100
        )
        .round(3)
    )

    return df


# ======================================================================
# SELECT BEST CANDIDATE PER PRODUCT
# ======================================================================

def select_best_candidates(
    df,
    cols
):

    print_section(
        "SELECTING BEST ALLOCATION PER PRODUCT"
    )

    product_col = cols["product"]

    # --------------------------------------------------------------
    # Sort strongest candidates first
    # --------------------------------------------------------------

    df = df.sort_values(

        by=[
            product_col,

            "optimization_score",

            cols["improvement"],

            cols["records"]
        ],

        ascending=[
            True,
            False,
            False,
            False
        ]
    )

    # --------------------------------------------------------------
    # Best candidate per product
    # --------------------------------------------------------------

    best = (

        df
        .groupby(
            product_col,
            as_index=False
        )
        .first()
    )

    best = best.reset_index(
        drop=True
    )

    # --------------------------------------------------------------
    # Global rank
    # --------------------------------------------------------------

    best = best.sort_values(
        "optimization_score",
        ascending=False
    )

    best["optimization_rank"] = range(
        1,
        len(best) + 1
    )

    print(
        f"\nProducts with optimized allocation: "
        f"{len(best)}"
    )

    return best


# ======================================================================
# RECOMMENDATION TYPE
# ======================================================================

def assign_recommendation_type(
    row,
    cols
):

    improvement_pct = row[
        cols["improvement_pct"]
    ]

    improvement_days = row[
        cols["improvement"]
    ]

    records = row[
        cols["records"]
    ]

    score = row[
        "optimization_score"
    ]

    # --------------------------------------------------------------
    # Strong
    # --------------------------------------------------------------

    if (

        improvement_pct >= 15

        and

        improvement_days >= 0.75

        and

        records >= 20

        and

        score >= 60

    ):

        return "Strong Reallocation"

    # --------------------------------------------------------------
    # High
    # --------------------------------------------------------------

    elif (

        improvement_pct >= 8

        and

        improvement_days >= 0.40

        and

        records >= 20

        and

        score >= 35

    ):

        return "High Potential"

    # --------------------------------------------------------------
    # Moderate
    # --------------------------------------------------------------

    elif (

        improvement_pct >= 4

        and

        improvement_days >= 0.15

        and

        records >= 20

        and

        score >= 20

    ):

        return "Moderate Potential"

    # --------------------------------------------------------------
    # Low
    # --------------------------------------------------------------

    else:

        return "Low Priority"


# ======================================================================
# BUILD FINAL RECOMMENDATIONS
# ======================================================================

def build_final_recommendations(
    best,
    cols
):

    best = best.copy()

    # --------------------------------------------------------------
    # Recommendation type
    # --------------------------------------------------------------

    best["recommendation_type"] = best.apply(

        lambda row:

        assign_recommendation_type(
            row,
            cols
        ),

        axis=1
    )

    # --------------------------------------------------------------
    # Estimated days saved
    #
    # Historical candidate records are used as the scale factor.
    # --------------------------------------------------------------

    best[
        "estimated_lead_time_days_saved"
    ] = (

        best[cols["improvement"]]

        *

        best[cols["records"]]
    )

    best[
        "estimated_lead_time_days_saved"
    ] = (

        best[
            "estimated_lead_time_days_saved"
        ]
        .round(3)
    )

    # --------------------------------------------------------------
    # Sort final recommendations
    # --------------------------------------------------------------

    best = best.sort_values(

        by=[
            "optimization_score",
            cols["improvement"],
            cols["records"]
        ],

        ascending=[
            False,
            False,
            False
        ]
    )

    # --------------------------------------------------------------
    # Final rank
    # --------------------------------------------------------------

    best["final_rank"] = range(
        1,
        len(best) + 1
    )

    return best


# ======================================================================
# PRODUCT SUMMARY
# ======================================================================

def create_product_summary(
    best,
    cols
):

    summary = best[
        [
            cols["product"],

            cols["location"],

            cols["current_lt"],

            cols["candidate_lt"],

            cols["improvement"],

            cols["improvement_pct"],

            cols["records"],

            "optimization_score",

            "recommendation_type"
        ]
    ].copy()

    summary.columns = [

        "Product ID",

        "Recommended Location",

        "Current Avg Lead Time",

        "Optimized Avg Lead Time",

        "Improvement Days",

        "Improvement Percent",

        "Historical Records",

        "Optimization Score",

        "Recommendation"
    ]

    return summary


# ======================================================================
# LOCATION SUMMARY
# ======================================================================

def create_location_summary(
    best,
    cols
):

    location_col = cols["location"]

    summary = (

        best

        .groupby(
            location_col
        )

        .agg(

            products_recommended=(
                cols["product"],
                "count"
            ),

            avg_improvement_days=(
                cols["improvement"],
                "mean"
            ),

            avg_improvement_pct=(
                cols["improvement_pct"],
                "mean"
            ),

            max_improvement_pct=(
                cols["improvement_pct"],
                "max"
            ),

            total_historical_records=(
                cols["records"],
                "sum"
            ),

            avg_optimization_score=(
                "optimization_score",
                "mean"
            )
        )

        .reset_index()
    )

    summary = summary.sort_values(

        "avg_optimization_score",

        ascending=False
    )

    return summary


# ======================================================================
# PORTFOLIO SUMMARY
# ======================================================================

def create_portfolio_summary(
    best,
    cols
):

    total_products = best[
        cols["product"]
    ].nunique()

    total_locations = best[
        cols["location"]
    ].nunique()

    avg_improvement_pct = best[
        cols["improvement_pct"]
    ].mean()

    avg_improvement_days = best[
        cols["improvement"]
    ].mean()

    total_days_saved = best[
        "estimated_lead_time_days_saved"
    ].sum()

    max_improvement_pct = best[
        cols["improvement_pct"]
    ].max()

    max_improvement_days = best[
        cols["improvement"]
    ].max()

    return {

        "products_optimized":
            total_products,

        "locations_involved":
            total_locations,

        "average_improvement_pct":
            avg_improvement_pct,

        "average_improvement_days":
            avg_improvement_days,

        "maximum_improvement_pct":
            max_improvement_pct,

        "maximum_improvement_days":
            max_improvement_days,

        "estimated_total_days_saved":
            total_days_saved
    }


# ======================================================================
# SAVE OUTPUTS
# ======================================================================

def save_outputs(
    qualified,
    best,
    product_summary,
    location_summary
):

    print_section(
        "SAVING OPTIMIZATION OUTPUTS"
    )

    # --------------------------------------------------------------
    # Complete optimization dataset
    # --------------------------------------------------------------

    optimization_path = (

        OUTPUT_DIR
        /
        "allocation_optimization.csv"
    )

    qualified.to_csv(
        optimization_path,
        index=False
    )

    # --------------------------------------------------------------
    # Final recommendations
    # --------------------------------------------------------------

    recommendations_path = (

        OUTPUT_DIR
        /
        "final_allocation_recommendations.csv"
    )

    best.to_csv(
        recommendations_path,
        index=False
    )

    # --------------------------------------------------------------
    # Product summary
    # --------------------------------------------------------------

    product_summary_path = (

        OUTPUT_DIR
        /
        "optimization_product_summary.csv"
    )

    product_summary.to_csv(
        product_summary_path,
        index=False
    )

    # --------------------------------------------------------------
    # Location summary
    # --------------------------------------------------------------

    location_summary_path = (

        OUTPUT_DIR
        /
        "optimization_location_summary.csv"
    )

    location_summary.to_csv(
        location_summary_path,
        index=False
    )

    print(
        "\nFiles created:"
    )

    print(
        f"\nOptimization candidates:\n"
        f"{optimization_path}"
    )

    print(
        f"\nFinal recommendations:\n"
        f"{recommendations_path}"
    )

    print(
        f"\nProduct summary:\n"
        f"{product_summary_path}"
    )

    print(
        f"\nLocation summary:\n"
        f"{location_summary_path}"
    )


# ======================================================================
# PRINT RESULTS
# ======================================================================

def print_results(
    best,
    portfolio,
    cols
):

    print_section(
        "FINAL OPTIMIZATION RESULTS"
    )

    print(
        f"Products optimized        : "
        f"{portfolio['products_optimized']}"
    )

    print(
        f"Locations involved         : "
        f"{portfolio['locations_involved']}"
    )

    print(
        f"Average improvement       : "
        f"{portfolio['average_improvement_pct']:.2f}%"
    )

    print(
        f"Average improvement days  : "
        f"{portfolio['average_improvement_days']:.2f}"
    )

    print(
        f"Best improvement          : "
        f"{portfolio['maximum_improvement_pct']:.2f}%"
    )

    print(
        f"Best improvement days     : "
        f"{portfolio['maximum_improvement_days']:.2f}"
    )

    print(
        f"Estimated total days saved: "
        f"{portfolio['estimated_total_days_saved']:.2f}"
    )

    # --------------------------------------------------------------
    # Top recommendations
    # --------------------------------------------------------------

    print_section(
        "TOP OPTIMIZED ALLOCATIONS"
    )

    display_cols = [

        cols["product"],

        cols["location"],

        cols["current_lt"],

        cols["candidate_lt"],

        cols["improvement"],

        cols["improvement_pct"],

        cols["records"],

        "optimization_score",

        "recommendation_type"
    ]

    display = best[
        display_cols
    ].head(15).copy()

    print(
        display.to_string(
            index=False
        )
    )

    # --------------------------------------------------------------
    # Best recommendation
    # --------------------------------------------------------------

    if len(best) > 0:

        top = best.iloc[0]

        print_section(
            "BEST OPTIMIZED ALLOCATION"
        )

        print(
            f"Product             : "
            f"{top[cols['product']]}"
        )

        print(
            f"Recommended location : "
            f"{top[cols['location']]}"
        )

        print(
            f"Current lead time    : "
            f"{top[cols['current_lt']]:.2f} days"
        )

        print(
            f"Optimized lead time  : "
            f"{top[cols['candidate_lt']]:.2f} days"
        )

        print(
            f"Improvement          : "
            f"{top[cols['improvement']]:.2f} days"
        )

        print(
            f"Improvement          : "
            f"{top[cols['improvement_pct']]:.2f}%"
        )

        print(
            f"Historical records   : "
            f"{int(top[cols['records']])}"
        )

        print(
            f"Optimization score   : "
            f"{top['optimization_score']:.2f}"
        )

        print(
            f"Recommendation       : "
            f"{top['recommendation_type']}"
        )


# ======================================================================
# MAIN
# ======================================================================

def main():

    print_header(
        "ALLOCATION OPTIMIZATION"
    )

    # --------------------------------------------------------------
    # STEP 1
    # Load Step 20 data
    # --------------------------------------------------------------

    df = load_impact_data()

    # --------------------------------------------------------------
    # STEP 2
    # Normalize column names
    # --------------------------------------------------------------

    df = normalize_columns(
        df
    )

    # --------------------------------------------------------------
    # STEP 3
    # Validate columns
    # --------------------------------------------------------------

    cols = validate_data(
        df
    )

    # --------------------------------------------------------------
    # STEP 4
    # Filter candidates
    # --------------------------------------------------------------

    qualified = filter_candidates(
        df,
        cols
    )

    # --------------------------------------------------------------
    # STEP 5
    # Calculate optimization score
    # --------------------------------------------------------------

    qualified = calculate_optimization_score(
        qualified,
        cols
    )

    # --------------------------------------------------------------
    # STEP 6
    # Select best candidate per product
    # --------------------------------------------------------------

    best = select_best_candidates(
        qualified,
        cols
    )

    # --------------------------------------------------------------
    # STEP 7
    # Build final recommendations
    # --------------------------------------------------------------

    best = build_final_recommendations(
        best,
        cols
    )

    # --------------------------------------------------------------
    # STEP 8
    # Product summary
    # --------------------------------------------------------------

    product_summary = create_product_summary(
        best,
        cols
    )

    # --------------------------------------------------------------
    # STEP 9
    # Location summary
    # --------------------------------------------------------------

    location_summary = create_location_summary(
        best,
        cols
    )

    # --------------------------------------------------------------
    # STEP 10
    # Portfolio summary
    # --------------------------------------------------------------

    portfolio = create_portfolio_summary(
        best,
        cols
    )

    # --------------------------------------------------------------
    # STEP 11
    # Save
    # --------------------------------------------------------------

    save_outputs(

        qualified,

        best,

        product_summary,

        location_summary
    )

    # --------------------------------------------------------------
    # STEP 12
    # Display results
    # --------------------------------------------------------------

    print_results(

        best,

        portfolio,

        cols
    )

    print_section(
        "ALLOCATION OPTIMIZATION COMPLETED"
    )


# ======================================================================
# ENTRY POINT
# ======================================================================

if __name__ == "__main__":

    main()