"""
23_Allocation_Visualization.py

Factory Reallocation & Shipping Optimization
Step 23: Allocation Visualization

Purpose
-------
Create professional visualizations from the final recommendation
dataset generated by Step 22.

This script is designed to work with the actual Step 22 schema,
where:

    candidate_avg_lead_time

is used instead of:

    recommended_avg_lead_time

Outputs
-------
data/processed/factory_allocation/visualizations/
    01_lead_time_comparison.png
    02_improvement_percentage.png
    03_decision_score.png
    04_recommendation_priority.png
    05_location_impact.png
    06_product_impact.png
    07_days_saved.png
    08_executive_dashboard.png
"""

from pathlib import Path
import sys

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJECT_ROOT / "data" / "processed" / "factory_allocation"

RECOMMENDATION_PATH = (
    DATA_DIR
    / "recommendations"
    / "final_recommendations.csv"
)

OUTPUT_DIR = (
    DATA_DIR
    / "visualizations"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# DISPLAY SETTINGS
# ============================================================

pd.set_option(
    "display.max_columns",
    None
)

pd.set_option(
    "display.width",
    180
)

pd.set_option(
    "display.max_rows",
    100
)


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def print_section(title):
    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)


def save_plot(filename):
    output_path = OUTPUT_DIR / filename

    plt.tight_layout()
    plt.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()

    print(f"Created: {output_path}")


# ============================================================
# LOAD DATA
# ============================================================

def load_data():

    print_section("LOADING STEP 22 RECOMMENDATION DATA")

    if not RECOMMENDATION_PATH.exists():

        raise FileNotFoundError(
            f"""
Final recommendation dataset not found.

Expected:
{RECOMMENDATION_PATH}

Run Step 22 first:

python notebooks\\22_Recommendation_Decision_Report.py
"""
        )

    print("Final recommendations:")
    print(RECOMMENDATION_PATH)

    df = pd.read_csv(
        RECOMMENDATION_PATH
    )

    print(
        f"\nDataset shape: {df.shape}"
    )

    return df


# ============================================================
# VALIDATE DATA
# ============================================================

def validate_data(df):

    print_section("VALIDATING RECOMMENDATION DATA")

    required_columns = [
        "product_id",
        "candidate_location",
        "current_avg_lead_time",
        "candidate_avg_lead_time",
        "lead_time_improvement_days",
        "lead_time_improvement_pct",
        "candidate_records",
        "decision_score",
        "priority",
        "confidence",
        "recommended_action",
    ]

    missing = [
        col
        for col in required_columns
        if col not in df.columns
    ]

    if missing:

        print("Missing columns:")

        for col in missing:
            print(f"- {col}")

        raise ValueError(
            "\nRequired columns are missing from the "
            "Step 22 recommendation dataset."
        )

    print("Required columns: OK")

    # --------------------------------------------------------
    # Important compatibility handling
    # --------------------------------------------------------

    if (
        "recommended_avg_lead_time"
        not in df.columns
    ):

        print(
            "\nColumn compatibility:"
        )

        print(
            "recommended_avg_lead_time not found."
        )

        print(
            "Using candidate_avg_lead_time "
            "as recommended_avg_lead_time."
        )

        df[
            "recommended_avg_lead_time"
        ] = df[
            "candidate_avg_lead_time"
        ]

    print(
        f"\nValid rows: {len(df):,}"
    )

    return df


# ============================================================
# CLEAN DATA
# ============================================================

def prepare_data(df):

    print_section("PREPARING VISUALIZATION DATA")

    numeric_columns = [
        "current_avg_lead_time",
        "candidate_avg_lead_time",
        "recommended_avg_lead_time",
        "lead_time_improvement_days",
        "lead_time_improvement_pct",
        "candidate_records",
        "decision_score",
        "optimization_score",
        "estimated_days_saved",
        "estimated_lead_time_days_saved",
    ]

    for col in numeric_columns:

        if col in df.columns:

            df[col] = pd.to_numeric(
                df[col],
                errors="coerce"
            )

    df["product_id"] = (
        df["product_id"]
        .astype(str)
    )

    df["candidate_location"] = (
        df["candidate_location"]
        .astype(str)
    )

    df["priority"] = (
        df["priority"]
        .astype(str)
    )

    df["confidence"] = (
        df["confidence"]
        .astype(str)
    )

    df["recommended_action"] = (
        df["recommended_action"]
        .astype(str)
    )

    df = df.dropna(
        subset=[
            "current_avg_lead_time",
            "candidate_avg_lead_time",
            "lead_time_improvement_pct",
        ]
    )

    print(
        f"Rows available for visualization: {len(df)}"
    )

    return df


# ============================================================
# 1. LEAD TIME COMPARISON
# ============================================================

def plot_lead_time_comparison(df):

    print_section(
        "1. LEAD TIME COMPARISON"
    )

    data = df.sort_values(
        "lead_time_improvement_days",
        ascending=False
    )

    labels = (
        data["product_id"]
        + "\n"
        + data["candidate_location"]
    )

    x = np.arange(len(data))

    width = 0.35

    plt.figure(
        figsize=(14, 7)
    )

    plt.bar(
        x - width / 2,
        data["current_avg_lead_time"],
        width,
        label="Current Lead Time"
    )

    plt.bar(
        x + width / 2,
        data["candidate_avg_lead_time"],
        width,
        label="Recommended Lead Time"
    )

    plt.xticks(
        x,
        labels,
        rotation=45,
        ha="right"
    )

    plt.ylabel(
        "Lead Time (Days)"
    )

    plt.xlabel(
        "Product / Recommended Location"
    )

    plt.title(
        "Current vs Recommended Lead Time"
    )

    plt.legend()

    save_plot(
        "01_lead_time_comparison.png"
    )


# ============================================================
# 2. IMPROVEMENT PERCENTAGE
# ============================================================

def plot_improvement_percentage(df):

    print_section(
        "2. LEAD-TIME IMPROVEMENT"
    )

    data = df.sort_values(
        "lead_time_improvement_pct",
        ascending=True
    )

    labels = (
        data["product_id"]
        + "\n"
        + data["candidate_location"]
    )

    plt.figure(
        figsize=(12, 7)
    )

    plt.barh(
        labels,
        data["lead_time_improvement_pct"]
    )

    plt.xlabel(
        "Lead-Time Improvement (%)"
    )

    plt.ylabel(
        "Allocation"
    )

    plt.title(
        "Lead-Time Improvement by Allocation"
    )

    save_plot(
        "02_improvement_percentage.png"
    )


# ============================================================
# 3. DECISION SCORE
# ============================================================

def plot_decision_score(df):

    print_section(
        "3. DECISION SCORE"
    )

    data = df.sort_values(
        "decision_score",
        ascending=True
    )

    labels = (
        data["product_id"]
        + "\n"
        + data["candidate_location"]
    )

    plt.figure(
        figsize=(12, 7)
    )

    plt.barh(
        labels,
        data["decision_score"]
    )

    plt.xlabel(
        "Decision Score"
    )

    plt.ylabel(
        "Allocation"
    )

    plt.title(
        "Allocation Decision Score"
    )

    save_plot(
        "03_decision_score.png"
    )


# ============================================================
# 4. PRIORITY DISTRIBUTION
# ============================================================

def plot_priority_distribution(df):

    print_section(
        "4. PRIORITY DISTRIBUTION"
    )

    priority_counts = (
        df["priority"]
        .value_counts()
    )

    plt.figure(
        figsize=(10, 6)
    )

    plt.bar(
        priority_counts.index,
        priority_counts.values
    )

    plt.xlabel(
        "Priority"
    )

    plt.ylabel(
        "Number of Recommendations"
    )

    plt.title(
        "Recommendation Priority Distribution"
    )

    plt.xticks(
        rotation=20,
        ha="right"
    )

    save_plot(
        "04_recommendation_priority.png"
    )


# ============================================================
# 5. LOCATION IMPACT
# ============================================================

def plot_location_impact(df):

    print_section(
        "5. LOCATION IMPACT"
    )

    location_summary = (
        df.groupby(
            "candidate_location"
        )
        .agg(
            products=(
                "product_id",
                "nunique"
            ),
            avg_improvement_pct=(
                "lead_time_improvement_pct",
                "mean"
            ),
            avg_improvement_days=(
                "lead_time_improvement_days",
                "mean"
            ),
            total_days_saved=(
                "estimated_days_saved",
                "sum"
            ),
        )
        .reset_index()
    )

    location_summary = (
        location_summary
        .sort_values(
            "avg_improvement_pct",
            ascending=True
        )
    )

    plt.figure(
        figsize=(12, 7)
    )

    plt.barh(
        location_summary[
            "candidate_location"
        ],
        location_summary[
            "avg_improvement_pct"
        ]
    )

    plt.xlabel(
        "Average Lead-Time Improvement (%)"
    )

    plt.ylabel(
        "Recommended Location"
    )

    plt.title(
        "Impact by Recommended Location"
    )

    save_plot(
        "05_location_impact.png"
    )

    location_summary.to_csv(
        OUTPUT_DIR
        / "location_visualization_summary.csv",
        index=False
    )


# ============================================================
# 6. PRODUCT IMPACT
# ============================================================

def plot_product_impact(df):

    print_section(
        "6. PRODUCT IMPACT"
    )

    product_summary = (
        df.groupby(
            "product_id"
        )
        .agg(
            improvement_pct=(
                "lead_time_improvement_pct",
                "max"
            ),
            improvement_days=(
                "lead_time_improvement_days",
                "max"
            ),
            days_saved=(
                "estimated_days_saved",
                "sum"
            ),
        )
        .reset_index()
    )

    product_summary = (
        product_summary
        .sort_values(
            "improvement_pct",
            ascending=True
        )
    )

    plt.figure(
        figsize=(12, 7)
    )

    plt.barh(
        product_summary[
            "product_id"
        ],
        product_summary[
            "improvement_pct"
        ]
    )

    plt.xlabel(
        "Lead-Time Improvement (%)"
    )

    plt.ylabel(
        "Product"
    )

    plt.title(
        "Product-Level Lead-Time Improvement"
    )

    save_plot(
        "06_product_impact.png"
    )

    product_summary.to_csv(
        OUTPUT_DIR
        / "product_visualization_summary.csv",
        index=False
    )


# ============================================================
# 7. ESTIMATED DAYS SAVED
# ============================================================

def plot_days_saved(df):

    print_section(
        "7. ESTIMATED DAYS SAVED"
    )

    if (
        "estimated_days_saved"
        in df.columns
    ):

        column = "estimated_days_saved"

    elif (
        "estimated_lead_time_days_saved"
        in df.columns
    ):

        column = (
            "estimated_lead_time_days_saved"
        )

    else:

        df["estimated_days_saved"] = (
            df["lead_time_improvement_days"]
            * df["candidate_records"]
        )

        column = "estimated_days_saved"

    data = df.sort_values(
        column,
        ascending=True
    )

    labels = (
        data["product_id"]
        + "\n"
        + data["candidate_location"]
    )

    plt.figure(
        figsize=(12, 7)
    )

    plt.barh(
        labels,
        data[column]
    )

    plt.xlabel(
        "Estimated Historical Days Saved"
    )

    plt.ylabel(
        "Allocation"
    )

    plt.title(
        "Estimated Shipping Days Saved"
    )

    save_plot(
        "07_days_saved.png"
    )


# ============================================================
# 8. EXECUTIVE DASHBOARD
# ============================================================

def create_executive_dashboard(df):

    print_section(
        "8. EXECUTIVE SUMMARY"
    )

    total_recommendations = len(df)

    products = (
        df["product_id"]
        .nunique()
    )

    locations = (
        df["candidate_location"]
        .nunique()
    )

    avg_improvement_pct = (
        df["lead_time_improvement_pct"]
        .mean()
    )

    avg_improvement_days = (
        df["lead_time_improvement_days"]
        .mean()
    )

    max_improvement_pct = (
        df["lead_time_improvement_pct"]
        .max()
    )

    max_improvement_days = (
        df["lead_time_improvement_days"]
        .max()
    )

    if "estimated_days_saved" in df.columns:

        total_days_saved = (
            df["estimated_days_saved"]
            .sum()
        )

    elif (
        "estimated_lead_time_days_saved"
        in df.columns
    ):

        total_days_saved = (
            df[
                "estimated_lead_time_days_saved"
            ].sum()
        )

    else:

        total_days_saved = (
            df[
                "lead_time_improvement_days"
            ]
            * df["candidate_records"]
        ).sum()

    best = df.loc[
        df[
            "lead_time_improvement_pct"
        ].idxmax()
    ]

    print(
        f"""
Recommendations          : {total_recommendations}
Products involved        : {products}
Locations involved       : {locations}

Average improvement      : {avg_improvement_pct:.2f}%
Average reduction        : {avg_improvement_days:.2f} days

Maximum improvement      : {max_improvement_pct:.2f}%
Maximum reduction        : {max_improvement_days:.2f} days

Estimated total days saved: {total_days_saved:.2f}

BEST RECOMMENDATION

Product                  : {best["product_id"]}
Recommended location     : {best["candidate_location"]}
Current lead time        : {best["current_avg_lead_time"]:.2f} days
Recommended lead time    : {best["candidate_avg_lead_time"]:.2f} days
Improvement              : {best["lead_time_improvement_days"]:.2f} days
Improvement              : {best["lead_time_improvement_pct"]:.2f}%
Historical records       : {int(best["candidate_records"])}
Priority                 : {best["priority"]}
Confidence               : {best["confidence"]}
Action                   : {best["recommended_action"]}
"""
    )

    # --------------------------------------------------------
    # Dashboard figure
    # --------------------------------------------------------

    fig = plt.figure(
        figsize=(14, 9)
    )

    ax = fig.add_subplot(111)

    ax.axis("off")

    dashboard_text = f"""
FACTORY ALLOCATION OPTIMIZATION
EXECUTIVE DASHBOARD

Recommendations Evaluated : {total_recommendations}
Products Involved         : {products}
Locations Involved        : {locations}

Average Lead-Time Improvement
{avg_improvement_pct:.2f}%

Average Lead-Time Reduction
{avg_improvement_days:.2f} days

Maximum Improvement
{max_improvement_pct:.2f}%

Estimated Historical Days Saved
{total_days_saved:.2f}

--------------------------------------------

BEST RECOMMENDATION

Product:
{best["product_id"]}

Recommended Location:
{best["candidate_location"]}

Current Lead Time:
{best["current_avg_lead_time"]:.2f} days

Recommended Lead Time:
{best["candidate_avg_lead_time"]:.2f} days

Improvement:
{best["lead_time_improvement_days"]:.2f} days
({best["lead_time_improvement_pct"]:.2f}%)

Priority:
{best["priority"]}

Confidence:
{best["confidence"]}

Recommended Action:
{best["recommended_action"]}
"""

    ax.text(
        0.5,
        0.5,
        dashboard_text,
        ha="center",
        va="center",
        fontsize=15,
        family="monospace"
    )

    plt.title(
        "Factory Reallocation Executive Dashboard",
        fontsize=20,
        pad=20
    )

    save_plot(
        "08_executive_dashboard.png"
    )


# ============================================================
# SAVE VISUALIZATION DATA
# ============================================================

def save_visualization_data(df):

    print_section(
        "SAVING VISUALIZATION DATA"
    )

    output_path = (
        OUTPUT_DIR
        / "visualization_dataset.csv"
    )

    df.to_csv(
        output_path,
        index=False
    )

    print(
        f"Visualization dataset:\n{output_path}"
    )


# ============================================================
# MAIN
# ============================================================

def main():

    print("\n")
    print("=" * 70)
    print("ALLOCATION VISUALIZATION")
    print("=" * 70)

    # --------------------------------------------------------
    # Load
    # --------------------------------------------------------

    df = load_data()

    # --------------------------------------------------------
    # Validate
    # --------------------------------------------------------

    df = validate_data(
        df
    )

    # --------------------------------------------------------
    # Prepare
    # --------------------------------------------------------

    df = prepare_data(
        df
    )

    # --------------------------------------------------------
    # Save clean visualization dataset
    # --------------------------------------------------------

    save_visualization_data(
        df
    )

    # --------------------------------------------------------
    # Generate plots
    # --------------------------------------------------------

    plot_lead_time_comparison(
        df
    )

    plot_improvement_percentage(
        df
    )

    plot_decision_score(
        df
    )

    plot_priority_distribution(
        df
    )

    plot_location_impact(
        df
    )

    plot_product_impact(
        df
    )

    plot_days_saved(
        df
    )

    create_executive_dashboard(
        df
    )

    # --------------------------------------------------------
    # Completion
    # --------------------------------------------------------

    print_section(
        "STEP 23 COMPLETED SUCCESSFULLY"
    )

    print(
        f"""
Visualization directory:

{OUTPUT_DIR}

Generated files:

1. 01_lead_time_comparison.png
2. 02_improvement_percentage.png
3. 03_decision_score.png
4. 04_recommendation_priority.png
5. 05_location_impact.png
6. 06_product_impact.png
7. 07_days_saved.png
8. 08_executive_dashboard.png

Additional files:

9.  visualization_dataset.csv
10. location_visualization_summary.csv
11. product_visualization_summary.csv
"""
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()